// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 마이그레이션/db push는 다이렉트 연결 사용 (풀러/PgBouncer는 DDL에 제약)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
